// src/stories/Booth.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './style.css';

export const Booth = ({ options }) => {
  return (
    <div>
      {
        options.map((option) => {
          return (
            <button>
              { option }
            </button>
          )
        })
      }
    </div>
  )
}

Booth.propTypes = {
  options: PropTypes.array,

  /**
   * Optional click handler
   */
   onVote: PropTypes.func,
};

Booth.defaultProps = {
  options: [],
  onVote: undefined
};

// src/stories/Booth.vue
<template>
  <div>
    <button
      v-for="option in options" :key="option"
      @click.prevent="$emit('onVote')"
      @keydown.enter="$emit('onVote')"
    >
      {{ option }}
    </button>
  </div>
</template>

<script>
export default {
  name: 'Booth',
  props: {
    options: {
      type: Array,
      required: true,
      default: () => []
    }
  }
}
</script>

<style>

</style>
