// src/stories/Results.vue
<template>
  <div>
    <ol>
      <li v-for="vote in votes" :key="vote">
        {{ `${vote.option} - ${vote.count} votes (${Math.round ((vote.count* 100) / totalVotes) }%)` }}
      </li>
    </ol>
  </div>
</template>

<script>
export default {
  name: 'Results',
  props: {
    votes: {
      type: Array,
      required: true,
      default: () => []
    }
  },
  computed: {
    totalVotes() {
      let total = 0
  
      this.votes.forEach(element => {
        total += element.count
      });

      return total
    }
  }
}
</script>

<style>

</style>

// src/stories/Results.jsx
import React from 'react';
import PropTypes from 'prop-types';

export const Results = ({ votes }) => {
  let total = 0
  
  votes.forEach(element => {
    total += element.count
  });

  return (
    <ol>
      {
        votes.map((option) => {
          const totalVotes = Math.round ((option.count* 100) / total)
          return (
            <li key={option.option}>
              {`${option.option} - ${option.count} votes (${!!totalVotes ? totalVotes :  0}%)`}
            </li>     
          )
        })
      }
    </ol>
  )
}

Results.propTypes = {
  votes: PropTypes.array,
};

Results.defaultProps = {
  votes: [],
};
