// src/stories/VotingCard.jsx
import React from 'react';
import PropTypes from 'prop-types';
import './votingCard.css';
import './style.css';

export const VotingCard = ({ title, state, votes, onVote }) => {

  let total = 0
  
  votes.forEach(element => {
    total += element.count
  });

  return (
    <div className="card-voting-wrapper">
      <h1>
        { title }
      </h1>
      {
        state ? (
          <div>
            <button onClick={onVote}>
              Sim
            </button>
            <button onClick={onVote}>
              Não
            </button>
          </div>
        ) : (
          <ol>
            {
              votes.map((option) => {
                return (
                  <li>
                    {`${option.option} - ${option.count} votes (${Math.round ((option.count* 100) / total) }%)`}
                  </li>     
                )
              })
            }
          </ol>
        )
      }
    </div>
  )
}

VotingCard.propTypes = {
  votes: PropTypes.array,
  title: PropTypes.string,
  state: PropTypes.bool,
  onVote: PropTypes.func
};

VotingCard.defaultProps = {
  votes: [],
  title: '',
  state: true,
  onVote: () => undefined,
};

// src/stories/VotingCard.svelte
<script>
  import { createEventDispatcher } from "svelte";
  import "./votingCard.css";

  export let votes = [
    {
      option: "Sim",
      count: 8,
    },
    {
      option: "Não",
      count: 3,
    },
  ];

  export let title = "Segue o relator?";

  export let state = true;

  function total() {
    let total = 0;

    votes.forEach((element) => {
      total += element.count;
    });

    return total;
  }

  const dispatch = createEventDispatcher();

  function onClick(event) {
    state = !state;
  }
</script>

<div class="card-voting-wrapper">
  <h1>
    {title}
  </h1>
  {#if state}
    <div class="card-voting-button-content">
      <button on:click={onClick}>Sim</button>
      <button on:click={onClick}>Não</button>
    </div>
  {/if}
  {#if !state}
    <div>
      <ol>
        {#each votes as vote, i}
          <li>
            {`${vote.option} - ${vote.count} votes (${Math.round(
              (vote.count * 100) / total()
            )}%)`}
          </li>
        {/each}
      </ol>
    </div>
  {/if}
</div>
